import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fpdart/fpdart.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/product.dart';
import '../../domain/repositories/product_repository.dart';
import '../models/product_model.dart';

class ProductRepositoryImpl implements ProductRepository {
  final FirebaseFirestore _firestore;

  ProductRepositoryImpl(this._firestore);

  @override
  Future<Either<Failure, List<Product>>> getProducts() async {
    try {
      final querySnapshot = await _firestore.collection('products').get();
      final products = querySnapshot.docs
          .map((doc) => ProductModel.fromFirestore(doc))
          .toList();
      return Right(products);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Product>> getProductById(String id) async {
    try {
      final docSnapshot = await _firestore.collection('products').doc(id).get();
      if (docSnapshot.exists) {
        return Right(ProductModel.fromFirestore(docSnapshot));
      } else {
        return const Left(ServerFailure('Product not found'));
      }
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> addProduct(Product product) async {
    try {
      // Create a document with the product ID if provided, otherwise letting Firestore generate one isn't handled by this method signature well unless ID is empty.
      // Assuming ID is generated by caller or we use random ID if empty. 
      // But typically we might let Firestore generate ID. 
      // For now, let's assume we pass the full model converted to JSON.
      // If ID is empty, we might want to use .add(), but Product entity has ID.
      // Let's use .set() with the ID.
      await _firestore.collection('products').doc(product.id).set((product as ProductModel).toJson());
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> deleteProduct(String id) async {
    try {
      await _firestore.collection('products').doc(id).delete();
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
