// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQkbHNkisLnXF5ghv3WP6F1Tq30IZQfM',
    appId: '1:464885274193:web:14a05bf6c98dda51bd4a70',
    messagingSenderId: '464885274193',
    projectId: 'e-commerse-app-ba4a0',
    authDomain: 'e-commerse-app-ba4a0.firebaseapp.com',
    storageBucket: 'e-commerse-app-ba4a0.firebasestorage.app',
    measurementId: 'G-1RVRR0GW8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhFKSd0suHzJAaoRW10Dh-kzIOeEJBvE',
    appId: '1:464885274193:android:944645ae98ed63bebd4a70',
    messagingSenderId: '464885274193',
    projectId: 'e-commerse-app-ba4a0',
    storageBucket: 'e-commerse-app-ba4a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnNOIdMt790Rj9uJF79IovSMZoJYguuA',
    appId: '1:464885274193:ios:621be574e09a3a79bd4a70',
    messagingSenderId: '464885274193',
    projectId: 'e-commerse-app-ba4a0',
    storageBucket: 'e-commerse-app-ba4a0.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHnNOIdMt790Rj9uJF79IovSMZoJYguuA',
    appId: '1:464885274193:ios:621be574e09a3a79bd4a70',
    messagingSenderId: '464885274193',
    projectId: 'e-commerse-app-ba4a0',
    storageBucket: 'e-commerse-app-ba4a0.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmQkbHNkisLnXF5ghv3WP6F1Tq30IZQfM',
    appId: '1:464885274193:web:dada012e91e47483bd4a70',
    messagingSenderId: '464885274193',
    projectId: 'e-commerse-app-ba4a0',
    authDomain: 'e-commerse-app-ba4a0.firebaseapp.com',
    storageBucket: 'e-commerse-app-ba4a0.firebasestorage.app',
    measurementId: 'G-SEDJKJZE62',
  );
}
